apiVersion: v1
kind: Node
metadata:
  name: worker-node01
  labels:
    blue: berry
    type: frontend
spec:
  taints:
  -  key: "blue"
     value: "berry"
     effect: "NoSchedule"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment-resource-pod
  annotations:
    kubernetes.ai/change-cause: "Version 1"
  labels:
    name: 2G-deployment
    type: 2G-deployment
spec:
  metadata:
    name: deployment-pod
    type: frontend
  spec:  
    containers:
    -  name: nginx pod
       image: nginx
    resources:
      requests:
        memory: "1 Gi"
        cpu: "2"
      limits:
        memory: "2 Gi"
        cpu: "3"
    replicas: 2
    selector:
      matchLabels:
        name: deployment-pod
        type: frontend
    tolerations:
    -  key: "blue"
       operator: "Equal"
       value: "berry"
       effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoreDuringExecution:
          nodeSelectorTerms:
          -  matchExpressions:
             -  key: "blue" 
                operator: "Equal"
                value: "berry" 
